'use client';
import { useState } from 'react';
import { Check, X } from 'lucide-react';
import { Checkbox } from '@/components/ui/checkbox';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { categories, skills, goals, equipment, intensityNames, type Exercise } from '@/lib/model';
import { validateExercise } from '@/lib/validation';
export function Choice({label,value,options,onChange,disabled=false}:{disabled?:boolean;label:string;value:string;options:(string|{value:string;label:string})[];onChange:(v:string)=>void}){
 const items=options.map(o=>typeof o==='string'?{value:o,label:o}:o);
 return <div className="choice"><span className="field-label">{label}</span><Select disabled={disabled} value={value} onValueChange={v=>v!==null&&onChange(v)}><SelectTrigger className="choice-trigger" aria-label={label}><SelectValue>{items.find(o=>o.value===value)?.label??value}</SelectValue></SelectTrigger><SelectContent>{items.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>;
}
export function Checks({options,value,onChange,label}:{options:readonly string[];value:string[];onChange:(v:string[])=>void;label?:string}){return <div>{label&&<span className="field-label">{label}</span>}<div className="chips">{options.map(o=><label key={o} className={'check-chip '+(value.includes(o)?'selected':'')}><Checkbox checked={value.includes(o)} onCheckedChange={checked=>onChange(checked?[...value,o]:value.filter(v=>v!==o))}/>{o}</label>)}</div></div>}
export function ExerciseForm({value,onSave,onCancel,submitLabel='Shrani vajo'}:{value:Exercise;onSave:(e:Exercise)=>void|Promise<void>;onCancel:()=>void;submitLabel?:string}){
 const [e,setE]=useState<Exercise>(structuredClone(value)),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const patch=(p:Partial<Exercise>)=>setE(v=>({...v,...p}));
 return <form className="exercise-form" onSubmit={async ev=>{ev.preventDefault();try{validateExercise(e);setBusy(true);await onSave(e);}catch(err){setError(err instanceof Error?err.message:'Vaje ni bilo mogoče shraniti.');}finally{setBusy(false);}}}><h3>Podrobnosti vaje</h3><label>Ime vaje<input required maxLength={160} value={e.name} onChange={v=>patch({name:v.target.value})}/></label><div className="form-grid"><Choice label="Kategorija" value={e.category} options={[...categories]} onChange={v=>patch({category:v as Exercise['category']})}/><Choice label="Intenzivnost" value={e.intensity} options={[...intensityNames]} onChange={v=>patch({intensity:v as Exercise['intensity']})}/><label>Trajanje (min)<input type="number" min={1} max={60} required value={e.duration} onChange={v=>patch({duration:Number(v.target.value)})}/></label></div><Choice label="Povezani element (za dovoljenja skupine)" value={e.skill??'Brez elementa'} options={['Brez elementa',...skills]} onChange={v=>patch({skill:v==='Brez elementa'?undefined:v as Exercise['skill']})}/><label className="check-chip"><Checkbox checked={e.performanceCheer!==false} onCheckedChange={v=>patch({performanceCheer:!!v})}/>Vaja je pregledana za performance cheer</label><p className="helper">Stare lastne vaje ostanejo shranjene, v nove treninge pa se vključijo po pregledu. Pri skoku, obratu ali gimnastičnem elementu izberi povezani element.</p><Checks label="Primerno za nivoje" options={['0','1','2','3']} value={e.levels.map(String)} onChange={v=>patch({levels:v.map(Number)})}/><Checks label="Cilji" options={goals} value={e.goals} onChange={v=>patch({goals:v})}/><Checks label="Potrebna oprema" options={equipment} value={e.equipment} onChange={v=>patch({equipment:v})}/><Checks label="Vaja vključuje" options={['Skoke','Oporo na zapestjih','Partnerja']} value={e.tags.map(t=>({jump:'Skoke',wrist:'Oporo na zapestjih',partner:'Partnerja'})[t]!).filter(Boolean)} onChange={v=>patch({tags:v.map(t=>({'Skoke':'jump','Oporo na zapestjih':'wrist','Partnerja':'partner'})[t]!)})}/><label>Navodila<textarea maxLength={3000} value={e.instructions} onChange={v=>patch({instructions:v.target.value})}/></label>{error&&<p role="alert" className="error">{error}</p>}<div className="actions"><button disabled={busy} className="primary" type="submit"><Check size={16}/>{busy?'Shranjujem …':submitLabel}</button><button type="button" className="secondary" onClick={onCancel}><X size={16}/>Prekliči</button></div></form>;
}
