import { type Exercise, type Category, type Intensity, type Skill } from './model';
type Drill={key:string;name:string;category:Category;instructions:string;goal?:string;equipment?:string[];tags?:string[];min?:number;skill?:Skill;duration?:number};
const drills:Drill[]=[
 {key:'tek',name:'Tek po prostoru z menjavo smeri',category:'Ogrevanje',goal:'Vzdržljivost',instructions:'Razporedi plesalke po robu prostora. Začnite z lahkim tekom; na znak menjajte smer ali preidite v stranske korake. Nato dodaj kratko hojo. Cilj je postopno ogrevanje, ne tekmovanje v hitrosti. Čas vključuje kratke prehode in razlago.'},
 {key:'par',name:'Zrcaljenje gibanja v paru',category:'Ogrevanje',goal:'Vzdržljivost',tags:['partner'],instructions:'V paru stojita obrnjeni druga proti drugi z dovolj razmika. Prva vodi lahke korake naprej, nazaj in v stran, druga jo zrcali. Po 30 sekundah zamenjajta vlogi in kratko počivajta. Brez vlečenja, nošenja ali sunkovitih menjav smeri.'},
 {key:'skipping',name:'Visoki skipping · 30 sekund / 10 sekund',category:'Ogrevanje',goal:'Vzdržljivost',tags:['jump'],instructions:'30 sekund izvajaj visok skipping na mestu, nato 10 sekund hodi. Trup ostane pokončen, roke sledijo teku. Začni z manjšim dvigom kolen, nato postopno povečuj gib. Ponovi z vmesnimi odmori, dokler traja vaja.'},
 {key:'jj',name:'Jumping jacks s high V in low V',category:'Ogrevanje',goal:'Vzdržljivost',tags:['jump'],instructions:'Iz vzporedne stoje z majhnim poskokom odpri noge in roke v high V. Ob priključku spusti roke v low V. Delaj 30 sekund, nato 10 sekund počivaj. Roke naj ustavijo gib na isto dobo, doskok je mehak.'},
 {key:'step',name:'Step touch in ogrevalne osmice',category:'Ogrevanje',goal:'Vzdržljivost',instructions:'Na glasbo stopi v stran in priključi drugo nogo, nato ponovi v drugo smer. Po dveh osmicah dodaj korake naprej in nazaj ter gibe rok. Izvajaj brez poskokov. Začni počasi in ohrani razdaljo do drugih.'},
 {key:'plank',name:'Plank – medved – strešica',category:'Ogrevanje',goal:'Moč',equipment:['Blazine'],tags:['wrist'],instructions:'Na blazini začni v opori na dlaneh. Iz planka približaj kolena proti položaju medveda in jih drži nizko nad tlemi, nato dvigni boke v strešico. Počasi menjaj položaje do ene minute, odloži kolena in počivaj. Ob izgubi nadzora skrajšaj serijo.'},
 {key:'deadbug-warm',name:'Stabilizacija trupa leže',category:'Ogrevanje',goal:'Moč',equipment:['Blazine'],instructions:'Lezi na hrbet, pokrči kolena in dvigni roke. Počasi iztegni eno nogo in nasprotno roko, nato ju vrni. Zamenjaj stran. Trup naj ostane miren; zmanjšaj obseg, če se začneš zvijati. Naredi kratko serijo, počivaj in ponovi.'},
 {key:'bridge-warm',name:'Dvigovanje medenice · obe nogi in L / D',category:'Ogrevanje',goal:'Moč',equipment:['Blazine'],instructions:'Leže pokrči kolena in postavi stopala na tla. Nadzorovano dviguj medenico 30 sekund na obeh nogah. Če medenica ostane ravna, dodaj po 15 sekund na vsaki nogi. Nato spusti medenico, počivaj in po potrebi ponovi.'},
 {key:'squat-warm',name:'Počepi in priprava na odriv',category:'Ogrevanje',goal:'Moč',instructions:'Iz stabilne stoje počasi izvedi počep in se vrni. Kolena sledijo stopalom. Po nekaj ponovitvah izteg poveži z dvigom na prste, brez skoka. Vmes se ustavi, preveri držo in ponovi.'},
 {key:'toe-warm',name:'Priprava za toe touch na tleh',category:'Ogrevanje',goal:'Moč',equipment:['Blazine'],instructions:'Sedi raznožno na blazino v udoben obseg, iztegni kolena in stopala. Trup drži pokončno. Izmenično malo dvigni eno nogo od tal in jo počasi spusti. Naredi kratko serijo na obe strani; brez sunkovitega nagibanja nazaj. To je aktivacija brez skoka.'},
 {key:'full-stretch',name:'Razteg telesa',category:'Razteg telesa',goal:'Gibljivost',duration:10,instructions:'Izvedite vaš običajni razteg celotnega telesa od glave do pete. Ta sklop sledi ogrevanju in ostane enak pri tehničnem, koreografskem in mešanem treningu.'},

 {key:'steps',name:'Prenosni koraki po prostoru',category:'Tehnika',instructions:'Po diagonali izvajaj korak–priključek in stranski korak s prenosom teže. Najprej brez rok, nato dodaj dogovorjen položaj rok. Na koncu diagonale se ustavi in vrni po robu. Menjaj začetno nogo, ohrani enakomerno štetje.'},
 {key:'tiptoe',name:'Hoja po špičkah',category:'Tehnika',instructions:'Dvigni pete in z majhnimi koraki prehodi kratko ravno pot. Trup ostane visok, gležnji naj ne uhajajo v stran. Spusti pete, počivaj in se vrni. Ne hodi po konicah prstov kot v baletnih špicah: teža je na sprednjem delu stopala.'},
 {key:'releve',name:'Relevé · dvigi na prste',category:'Tehnika',instructions:'Stoj ob stabilni opori, počasi dvigni pete in jih nadzorovano spusti. Začni z do 15 ponovitvami na obeh nogah. Če je os stabilna, nadaljuj z do 10 na vsaki nogi. Med serijami počivaj; število zmanjšaj pred izgubo kakovosti.'},
 {key:'passe',name:'Passé in priprava relevé–passé',category:'Tehnika',instructions:'Ob stabilni opori dvigni nogo v passé, zadrži in vrni; trener določi položaj stopala in kolka. Do osem ponovitev na vsako stran. Nato do šest samostojnih relevéjev in do šest povezav relevé–passé. Med serijami počivaj. Cilj je mirna os brez obrata.'},
 {key:'focus',name:'Vaja za fokus in spotting',category:'Tehnika',instructions:'Izberi stalno točko v višini oči. S počasnimi majhnimi koraki se obračaj okoli svoje osi. Po trenerjevem prikazu pogled vračaj na isto točko in zaključi v stabilni stoji. Po vsakem krogu se ustavi; najprej vadi počasi na obe strani.'},
 {key:'kick',name:'Kontrolirani kicki',category:'Tehnika',instructions:'Ob stabilni opori dvigni iztegnjeno nogo naprej v nadzorovan obseg in jo počasi vrni. Ne vrzi trupa nazaj. Ponovi na vsako stran, nato enako v stran po trenerjevem prikazu. Višina je manj pomembna od iztegnjenega stopala, mirne medenice in nadzora.'},
 {key:'tendu',name:'Tendu · izteg stopala in linija noge',category:'Tehnika',instructions:'Iz stabilne stoje podrsaj s stopalom naprej do iztega in ga vrni. Nato ponovi v stran in nazaj. Teža ostane nad stojno nogo, koleno gibajoče se noge je iztegnjeno. Po kratki seriji zamenjaj nogo.'},
 {key:'arms',name:'Čiste pom linije na osmico',category:'Tehnika',instructions:'Izberi high V, low V in T. Na štetje prehajaj med njimi in vsak položaj jasno ustavi. Trener preveri enako višino rok ter smer dlani. Najprej počasi, nato poveži dve osmici v ritmu pesmi.'},
 {key:'arms-path',name:'Poti rok in natančni zaključki',category:'Tehnika',instructions:'Trener določi štiri osvojene položaje rok. Najprej vadi samo prehod med prvima dvema brez dodatnega zamaha. Dodaj druga dva in poveži osmico. Ekipa preveri skupen prihod v končni položaj; ponovi z drugo začetno stranjo.'},
 {key:'pom',name:'Poudarki s pomponi',category:'Tehnika',equipment:['Pomponi'],instructions:'Na štiri poudarke v glasbi izvedite dogovorjene pom položaje. Po vsakem poudarku ustavite gib pomponov. Najprej samo roke, nato dodajte preprost step touch. Preverite simetrijo in sproščena ramena.'},
 {key:'toe-prep',name:'Toe touch · predpriprava brez odriva',category:'Tehnika',equipment:['Blazine'],instructions:'Na blazini v raznožnem sedu izmenično aktivno dviguj iztegnjeni nogi v majhnem obsegu. Nato vstani ter brez skoka vadi pripravo rok in izteg telesa za toe touch. Razdeli delo v kratke serije z odmori; ne sili raznoženja.'},
 {key:'kick-line',name:'Kicki v skupni liniji',category:'Tehnika',goal:'Usklajenost',instructions:'V vrsti z dovolj razmika izvedite štiri nadzorovane kicke naprej na skupno štetje. Dogovorite se za višino, ki jo vse dosežejo s pravilno držo. Ustavite se in preverite roke ter zaključke, nato ponovite z drugo nogo.'},
 {key:'strength',name:'Počepi za moč in stabilnost',category:'Kondicija',goal:'Moč',instructions:'Izvedi osem počasnih počepov v udobnem obsegu, nato počivaj. Kolena usmeri v smer stopal, trup ohrani miren. Naslednjo serijo poveži s počasnim dvigom na prste. Ponavljaj kratke kakovostne serije.'},
 {key:'vups',name:'Dvigovanje trupa in V-up',category:'Kondicija',goal:'Moč',equipment:['Blazine'],min:1,instructions:'Leže na blazini izvedi do osem nadzorovanih dvigov trupa po trenerjevem prikazu. Če skupina že obvlada V-up, poveži dvig trupa in nog; sicer uporabi pokrčena kolena. Spuščaj se počasi, brez zaganjanja vratu. Po seriji počivaj.'},
 {key:'band',name:'Stranski koraki z elastiko',category:'Kondicija',goal:'Moč',equipment:['Elastike'],instructions:'Trener pokaže namestitev kratke elastike in izbere primeren upor. V stabilni rahlo pokrčeni stoji naredi nekaj majhnih korakov v stran, nato nazaj. Medenica ostane mirna. Med serijami sprosti napetost in počivaj.'},
 {key:'weight',name:'Nadzor rok z utežmi 0,5 kg',category:'Kondicija',goal:'Moč',equipment:['Uteži 0,5 kg'],min:2,instructions:'Trener najprej preveri primernost lahkih ročnih uteži. Stoje počasi dviguj roke v izbran nadzorovan obseg in jih počasi spuščaj. Izvedi kratko serijo, nato odloži uteži in počivaj. Vajo izvajaj brez skokov, obratov in hitrih zamahov.'},

 {key:'pencil',name:'Svinčnik',category:'Skoki',skill:'Svinčnik',tags:['jump'],instructions:'Po osvojeni pripravi izvedi majhen navpični skok z iztegnjeno linijo telesa. Mehko doskoči in se povsem ustavi. Trener preveri skupen odriv, položaj rok in stabilnost. Ponovi posamezne poskuse z odmori.'},
 {key:'x',name:'X-skok',category:'Skoki',skill:'X-skok',tags:['jump'],instructions:'Trener pokaže odriv iz stabilne priprave in odpiranje rok ter nog v X. Začni z nizkim skokom. Noge pred doskokom zberi, mehko doskoči in se ustavi. Med poskusi popravi en dogovorjen detajl.'},
 {key:'tt',name:'Toe touch (TT)',category:'Skoki',skill:'Toe touch',tags:['jump'],instructions:'Najprej opravi aktivno pripravo na tleh ter preveri stabilen odriv in doskok. Po trenerjevem prikazu izvedi posamezen toe touch: uskladi pot rok in raznoženje, ohrani trup ter zberi noge za nadzorovan doskok. Med poskusi se ustavi. Višine ne povečuj na račun tehnike.'},
 {key:'tt-sync',name:'Toe touch na skupno štetje',category:'Skoki',skill:'Toe touch',goal:'Usklajenost',tags:['jump'],instructions:'Uporabite že osvojen toe touch. Dogovorite se za dobo priprave, odriva in zaključka. Manjša skupina izvede en poskus, druga spremlja istočasnost. Po povratni informaciji zamenjajte skupini in ponovite.'},
 {key:'jete',name:'Jeté po diagonali',category:'Skoki',skill:'Jeté',tags:['jump'],instructions:'Najprej brez velikega skoka ponovi trenerjev vhod s prenosnimi koraki. Nato izvedi posamezen že naučen jeté po prosti diagonali. Ohranjen izteg nog in stopal prilagodi aktivni gibljivosti ter nadzoruj doskok. Vadite obe strani in se vračajte po robu.'},
 {key:'split',name:'Split leap',category:'Skoki',skill:'Split leap',tags:['jump'],instructions:'Trener najprej preveri osvojen odriv in izbere vhod. Izvedi posamezen split leap z nadzorovanim iztegom nog naprej in nazaj ter mehkim zaključkom. Ne sili razpona do špage. Med poskusi počivaj in menjaj vodilno nogo.'},
 {key:'double-tt',name:'Dvojni toe touch',category:'Skoki',skill:'Dvojni toe touch',tags:['jump'],instructions:'Samo za skupino, ki ji je trener dovolil vadbo povezave in že obvlada posamezen toe touch. Po prikazu poveži dva v dogovorjenem ritmu. Preveri kakovost drugega odriva in doskoka. Če se linija ali nadzor podreta, vadi posamezne poskuse.'},
 {key:'calypso',name:'Calypso · ponavljanje osvojenega elementa',category:'Skoki',skill:'Calypso',tags:['jump'],instructions:'Trener preveri, da je element že naučen, ter pokaže vaš dogovorjeni vhod in zaključek. Vadite posamično v prosti diagonali, najprej vhod in doskok ločeno, nato celoten calypso. Med poskusi počivajte. To je drill pod vodstvom trenerja, ne samostojno učenje novega elementa.'},
 {key:'switch',name:'Switch leap · ponavljanje osvojenega elementa',category:'Skoki',skill:'Switch leap',tags:['jump'],instructions:'Po osvojenem osnovnem split leapu trener preveri naučeno menjavo nog. Najprej ponovi vhod, nato posamezen switch leap. Spremljaj ritem menjave in nadzor doskoka, ne največje širine. Med poskusi počivaj in vadi obe strani po trenerjevem izboru.'},
 {key:'tilt',name:'Tilt jump · ponavljanje osvojenega elementa',category:'Skoki',skill:'Tilt jump',tags:['jump'],instructions:'Trener preveri aktivno obvladan tilt položaj ter že naučen odriv in doskok. Najprej označi vhod brez skoka, nato izvedi posamezen osvojen tilt jump z dovolj prostora. Po vsakem poskusu se ustavi in popravi izbran detajl.'},
 {key:'partial',name:'Obrati ¼, ½ in ¾',category:'Obrati',skill:'Delni obrati',instructions:'Začni iz osvojene priprave relevé–passé. Izvedi četrt obrata in se stabilno ustavi. Šele ob urejenem zaključku trener doda polovico in tri četrt obrata. Menjaj strani, vračaj pogled na fokus in med poskusi ponovno postavi pripravo.'},
 {key:'single',name:'Enojna pirueta',category:'Obrati',skill:'Enojna pirueta',instructions:'Predpogoj sta stabilen relevé–passé in nadzorovan delni obrat. Trener pokaže vaš začetni položaj. Izvedi eno pirueto, vrni pogled na fokus in zaključi v dogovorjeni položaj. Po poskusu se ustavi, preveri os in ponovi na obe strani.'},
 {key:'single-sync',name:'Enojna pirueta na osmico',category:'Obrati',skill:'Enojna pirueta',goal:'Usklajenost',instructions:'Že osvojeno enojno pirueto vključite v osmico: dogovorite pripravo, obrat in skupen zaključek. Vadite v manjših skupinah na štetje, nato na glasbo. Cilj je istočasnost, ne dodatna rotacija.'},
 {key:'double',name:'Dvojna pirueta',category:'Obrati',skill:'Dvojna pirueta',instructions:'Za plesalke z zanesljivo enojno pirueto in že naučeno dvojno različico, ki jo je trener vključil med dovoljene elemente. Iz urejene priprave izvedi dvojno pirueto ter stabilen zaključek. Med poskusi počivaj. Če se os poruši, se vrni na enojno različico.'},
 {key:'floor',name:'Plesna osmica v sedu in na boku',category:'Parter',equipment:['Blazine'],instructions:'Trener sestavi kratko povezavo sed – položaj na boku – izteg nog – sed. Vsak položaj najprej vadi ločeno, nato jih poveži v osem dob. Uskladi linije stopal, rok in pogleda. Vaja poteka brez skokov, dvigov ali letnih elementov.'},
 {key:'wheel',name:'Kolo v plesni povezavi',category:'Parter',skill:'Kolo',equipment:['Blazine'],tags:['wrist'],instructions:'Samo ponavljanje že osvojenega kolesa po trenerjevem prikazu. Po eni plesalki v prosti diagonali povežite plesni vhod, posamezno kolo in stabilen zaključek. Trener preveri smer ter linije. Nato označite povezavo na glasbo.'},
 {key:'one-hand',name:'Kolo z eno roko · osvojen element',category:'Parter',skill:'Kolo z eno roko',equipment:['Blazine'],tags:['wrist'],instructions:'Vključeno samo, če trener potrdi obvladovanje kolesa z eno roko za to skupino. Pod njegovim neposrednim vodstvom ponavljaj dogovorjen vhod, osvojen element in zaključek. Vadite posamično na ustrezni prosti podlagi. Ne uvajaj prehoda iz navadnega kolesa brez strokovne priprave.'},
 {key:'aerial',name:'Kolo brez rok · osvojen element',category:'Parter',skill:'Kolo brez rok',equipment:['Blazine'],tags:['jump'],instructions:'Samo ponavljanje že obvladanega kolesa brez rok za plesalke, ki jih je trener izrecno izbral. Trener določi ustrezno podlago, prostor in izvedbo. Po posamičnem poskusu preveri zaključek ter vključi element v kratko plesno povezavo. Ta opis ni navodilo za prvo učenje elementa.'},

 {key:'learn-choreo',name:'Ustvarjanje in učenje koreografije',category:'Koreografija',instructions:'Izberite odlomek mixa in dve osmici. Trener pokaže korake, skupina jih najprej ponovi brez rok. Dodajte roke in pogled, nato vse povežite na štetje. Na koncu ponovite na isti odlomek glasbe. Skoke in obrate v tem delu označite brez polne izvedbe.'},
 {key:'clean-choreo',name:'Čiščenje koreografije po osmicah',category:'Koreografija',goal:'Usklajenost',instructions:'Izberite že naučeni dve do štiri osmice. Ustavite na pomembnih dobah in primerjajte položaje rok, smer telesa ter razdalje. Popravite največ dva detajla, nato ponovite povezano na glasbo. Elemente po potrebi označite, da ostane poudarek na enotnosti.'},
 {key:'formation',name:'Formacije in prehodi na mix',category:'Koreografija',goal:'Usklajenost',instructions:'Določite začetna in končna mesta. Vsaka plesalka s hojo prehodi svojo pot do iste dogovorjene dobe. Preverite križanja in razdalje. Nato dodajte osvojene korake in roke ter ponovite na glasbo, brez dodatnih skokov.'},
 {key:'music',name:'Glasbeni poudarki in prehod med pesmima',category:'Koreografija',goal:'Usklajenost',instructions:'Poslušajte zadnjo osmico prve pesmi in prvi dve naslednje. Označite spremembo tempa in ključne poudarke. Najprej prehodite korake, nato dodajte roke in izraz. Uskladite prihod na prvo dobo novega odseka; elemente označite brez izvedbe.'},
 {key:'connect',name:'Povezovanje odsekov koreografije',category:'Koreografija',goal:'Vzdržljivost',instructions:'Povežite dva že osvojena odseka koreografije na isti mix. Začnite nekaj dob pred stikom, da vadite dejanski prehod. V tej vaji skoke, obrate in gimnastične elemente označite; polna izvedba dovoljenih elementov je v ločenem tehničnem drillu. Po prehodu počivajte in ponovite popravljeni odlomek.'},
 {key:'routine',name:'Koreografija z elementi skupine',category:'Koreografija',goal:'Vzdržljivost',instructions:'Izvedite osvojen odlomek koreografije na vaš mix. Polno izvedite samo dovoljene elemente iz koreografije, ki ustrezajo omejitvam tega treninga in jih vse vključene plesalke že obvladajo. Preostale elemente označite brez izvedbe. Po prehodu počivajte, izberite dva popravka in ponovite odlomek.'},
 {key:'cooldown',name:'Lažji zaključni razteg',category:'Zaključni razteg',goal:'Gibljivost',duration:5,instructions:'Izvedite vaš običajni lažji razteg za razbremenitev mišic po treningu. Umirite dihanje in zaključite brez povečevanja zahtevnosti ali obsega.'},
];
// A second organization of each element gives replacement a real, equally scoped drill.
const skillVariants:Drill[]=drills.filter(d=>d.skill&&d.goal!=='Usklajenost').map(d=>({...d,key:d.key+'-correction',name:d.name.split(' · ')[0]+' · poskus, popravek, ponovitev',instructions:d.instructions+' Organizacija te različice: izvedi en poskus, s trenerjem izberi samo en popravek, nato ponovi isti element. Po treh poskusih počivaj; ne dodajaj novega elementa ali težje različice.'}));
export const catalog:Exercise[]=[...drills,...skillVariants].flatMap(d=>{
 const lowOnly=d.category==='Razteg telesa'||d.category==='Zaključni razteg';
 const intensities:Intensity[]=lowOnly?['Nizka']:['Nizka','Srednja','Visoka'];
 return intensities.map(intensity=>({id:'pc-'+d.key+'-'+intensity,name:d.name,category:d.category,levels:[0,1,2,3].filter(n=>n>=(d.min??0)),duration:d.duration??6,intensity,equipment:d.equipment??[],goals:[d.goal??'Tehnika'],tags:d.tags??[],instructions:d.instructions+(lowOnly?'':intensity==='Nizka'?' Kratke serije in daljši odmori.':intensity==='Visoka'?' Več kratkih serij z odmori; zahtevnost elementa ostaja enaka.':' Enakomerno izmenjuj delo, povratno informacijo in odmor.'),performanceCheer:true,...(d.skill?{skill:d.skill}:{})}));
});
