import { categories, skills, goals, equipment, restrictions, intensityNames, type Exercise, type Group, type Settings, type Training } from './model';
function check(ok:unknown,message='Podatki niso veljavni.'):asserts ok{if(!ok)throw new Error(message);}
const obj=(x:any)=>check(x&&typeof x==='object'&&!Array.isArray(x));
const str=(x:any,max=5000)=>check(typeof x==='string'&&x.length<=max);
const num=(x:any,min:number,max:number)=>check(Number.isInteger(x)&&x>=min&&x<=max);
const list=(x:any,allowed:readonly string[])=>check(Array.isArray(x)&&x.length<=allowed.length&&new Set(x).size===x.length&&x.every(v=>allowed.includes(v)));
const id=(x:any)=>check(typeof x==='string'&&/^[\p{L}\p{N} _+.-]{1,120}$/u.test(x));
export function validatePreference(p:any){obj(p);id(p.id);check(['off','favorite','always'].includes(p.mode),'Izberi veljavno pogostost vaje.');}
export function validateSettings(s:any):asserts s is Settings{obj(s);id(s.groupId);num(s.level,0,3);num(s.duration,20,180);list(s.focus,categories);list(s.goals,goals);list(s.equipment,equipment);list(s.restrictions,restrictions);check(intensityNames.includes(s.intensity));str(s.description);str(s.details);if(s.varyWarmup!==undefined)check(typeof s.varyWarmup==='boolean');if(s.techniquePercent!==undefined)num(s.techniquePercent,10,100);if(s.allowedSkills!==undefined)list(s.allowedSkills,skills);if(s.choreographySkills!==undefined){list(s.choreographySkills,skills);check(s.choreographySkills.every((k:string)=>(s.allowedSkills??[]).includes(k)),'Elementi koreografije morajo biti med dovoljenimi elementi.');}}
export function validateExercise(e:any):asserts e is Exercise{obj(e);id(e.id);str(e.name,160);check(e.name.trim().length>0,'Vpiši ime vaje.');check(categories.includes(e.category));check(Array.isArray(e.levels)&&e.levels.length>0&&e.levels.length<=4);e.levels.forEach((n:any)=>num(n,0,3));num(e.duration,1,60);check(intensityNames.includes(e.intensity));list(e.equipment,equipment);list(e.goals,goals);check(e.goals.length>0,'Izberi vsaj en cilj.');list(e.tags,['jump','wrist','partner']);str(e.instructions,3000);if(e.skill!==undefined)check(skills.includes(e.skill));if(e.performanceCheer!==undefined)check(typeof e.performanceCheer==='boolean');}
export function validateGroup(g:any):asserts g is Group{obj(g);id(g.id);str(g.name,100);check(g.name.trim().length>0,'Vpiši ime skupine.');num(g.level,0,3);num(g.members,1,100);str(g.notes,2000);if(g.sessionsPerWeek!==undefined)num(g.sessionsPerWeek,1,7);if(g.defaultDuration!==undefined)num(g.defaultDuration,20,180);if(g.allowedSkills!==undefined)list(g.allowedSkills,skills);if(g.choreographySkills!==undefined){list(g.choreographySkills,skills);check(g.choreographySkills.every((k:string)=>(g.allowedSkills??[]).includes(k)),'Najprej dovoli element za vadbo.');}}
export function validateTraining(t:any):asserts t is Training{
 obj(t);id(t.id);str(t.title,160);check(t.title.trim().length>0,'Vpiši naslov treninga.');check(typeof t.date==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(t.date)&&!Number.isNaN(Date.parse(t.date)));validateSettings(t.settings);num(t.revision,0,1000000);str(t.updatedAt,100);
 check(Array.isArray(t.blocks)&&t.blocks.length<=30);let count=0;const ids=new Set();for(const b of t.blocks){obj(b);id(b.id);check(!ids.has(b.id));ids.add(b.id);check(categories.includes(b.category));check(Array.isArray(b.items));for(const e of b.items){id(e.instanceId);check(!ids.has(e.instanceId));ids.add(e.instanceId);str(e.notes,3000);validateExercise(e);count++;}}check(count<=200);check(Array.isArray(t.warnings)&&t.warnings.length<=50);t.warnings.forEach((w:any)=>str(w,1000));
}

